#!/bin/bash

DEBUG=0
DISCLMAINERS=1

readonly PREFIX_LENGTH=3
readonly WORD_FILE="monero25-english.md"

ENTROPY=264 #needed to generate 256 bits of entropy
LAST_HEX_WORD="65A"
LAST_WORD_INDEX=1626

SEED_WORDS=24

# Dice faces, default is 6 => D6
# Note: if you have 2 faces, you are probably flipping a coin :)
dice_faces=6

# The full sequence entered from prompt, contain the resuls achieved by the throws of dices or coins
dice_throws_sequence=''

show_help() {
	local bold=$'\033[1m'
    local reset=$'\033[0m'
	local dim=$'\033[2m'
    local cyan=$'\033[36m'
cat <<EOF
Usage: $0 [OPTIONS]

Description:
Generate Monero Legacy Seed words from physical dice rolls - offline, transparent, and privacy-focused.

Options:
${bold}-h${reset}			Show this help message 
${bold}-d${reset}			Execute without disclaimer
${bold}-s${reset}			The numbers rolled on the dice, witout spaces	[required]
${bold}-f${reset}			The number of faces of the dice
			[default: 6]

Examples:
Generate 25 words seed from default D6 dice throws
${dim}$ bash $0 -s 123124465261[...]4135612546${reset}

Generate 25 words seed from coin flipping
${dim}$ bash $0 -s 1212122222[...]122222211 -f 2 

Generate 25 words seed from D8
${dim}$ bash $0 -s 123124465261[...]5612546 -f 8 		
EOF
}

all_in_range() {
    local lo=1 hi=$dice_faces
    shift 2
	returnValue=0

	for ((x=0; x<${#dice_throws_sequence}; x++)); do
		val=${dice_throws_sequence:x:1}
		if (( val < lo || val > hi )); then 
			returnValue=1
			break
		fi
	done

    echo $returnValue
}

while getopts "hf:s:d" opt; do
	case $opt in
		h) show_help && exit 0;;
		f) dice_faces=$(echo $OPTARG);;
		d) DISCLMAINERS=0;;
		s) dice_throws_sequence=$(echo $OPTARG | tr -d ' ');;
  	esac
done

if [ $DISCLMAINERS -eq 1 ]; then
	while : 
	do
		clear
		cat<<EOF
========================================================================================================================
Disclaimer 1: This software and any outputs it generates are provided “as is” and without warranties of any kind, 
express or implied. The authors and contributors make no representations regarding the accuracy, reliability, security, 
legality, or suitability of the software or its outputs.
You are solely responsible for reviewing, validating, testing, and appropriately using any output generated by this software 
before relying on it or distributing it. The software may produce inaccurate, incomplete, biased, harmful, 
or otherwise unsuitable results.
To the fullest extent permitted by applicable law, the authors and contributors shall not be liable for any direct, 
indirect, incidental, consequential, or other damages, losses, claims, or liabilities arising from or related to the use 
of this software or its outputs.
Use of this software is at your own risk.

Disclaimer 2: Monero legacy seeds have 256 bits of entropy. The script request you to insert 512 entropy because you need to generate
exactly 24 words. These words have 10.6 bits and rounded to 11 you achieve a range between 00000000001 and 11001011010.
If the entropy generate a number above this range, the script skip it and pass to the next value in the goal to achieve the final 24 words.
For more details read the README.

To skip these disclaimers in future pass the option -d

---------------------------
Enter any key to accept:
EOF
	read -n1 -s
	clear
	break;
done
fi

checkInsertedNumbers=$(all_in_range)

if [[ ${checkInsertedNumbers} -eq 1 ]]; then 
	echo "ERROR: You must insert number between 1 and $dice_faces"	
	exit 1
fi

# Convert dice throws sequence in a hash sha256, so it's pointless to get more entropy
sha512value=$(sha512sum <<<$dice_throws_sequence | awk '{print $1}')


# Calculate the number of rolls needed, based on how many faces have the dices
base_entropy=$(echo "l($dice_faces)/l(2)" | bc -l)
needed_number_of_rolls=$(bc -l <<< "$ENTROPY / $base_entropy")

# Round result to units
needed_number_of_rolls=$(awk -v rolls="$needed_number_of_rolls" 'BEGIN { printf "%.0f\n", rolls }')

# We use sha512 to achieve more results, because some of it are not appropriate.
# Monero have 1626 words = 10.6 bits, so we need to use 11 bits that reach 2048 values.
# so if it's returned a value above the last word
# ignore it and go to the next value achieved.
needed_number_of_rolls=$(( needed_number_of_rolls * 2 ))

printf "%-20s %-10s\n" "Param" "Value"
echo "----------------------------"
printf "%-20s %-10s\n" "Entropy" "$ENTROPY"
printf "%-20s %-10s\n" "Dice Faces" "$dice_faces"
printf "%-20s %-10s\n" "Needed throws" "$needed_number_of_rolls"
printf "%-20s %-10s\n" "Inserted throws" "${#dice_throws_sequence}"
echo "----------------------------"

echo -e "\nInserted sequence:\n$dice_throws_sequence\n"


if [ $DEBUG -eq 0 ]; then
	if [ ${#dice_throws_sequence} -lt $needed_number_of_rolls ]; then 
		echo "ERROR: you need at least $needed_number_of_rolls values."	
		exit 1
	fi
fi

echo -e "Generated SHA512 from sequence:\n$sha512value \n"

# Lookup table for binary conversion
hex2bin=(0000 0001 0010 0011 0100 0101 0110 0111 1000 1001 1010 1011 1100 1101 1110 1111)

BINARY_CONVERSION=""
for (( i=0; i<${#sha512value}; i++ )); do
    hexValue=$((16#${sha512value:$i:1}))
	BINARY_CONVERSION+=${hex2bin[hexValue]}
done

# Original words from here https://github.com/monero-project/monero/blob/master/src/mnemonics/english.h
if [[ $DEBUG -eq 0 && ! -f ${WORD_FILE} ]]; then
	# Download Monero English word list
	wget -O ${WORD_FILE} https://raw.githubusercontent.com/SafeKeys/monero-mnemonic-seeds/refs/heads/main/mnemonics/english.md
	echo -e "\n"
fi

declare -A moneroLegacySeedwords
j=1
while IFS= read -r line; do
	moneroLegacySeedwords[$j]=$line
	((j++))
done < <(cat ${WORD_FILE} | tail -n +3 | awk '{print $4}')


declare -A finalMatrix
i=1
while IFS= read -r group; do
	decimalConversion=$((2#$group+1))
	finalMatrix["$i,0"]=$group
	finalMatrix["$i,1"]=$decimalConversion
	finalMatrix["$i,2"]=${moneroLegacySeedwords[$decimalConversion]}
	finalMatrix["$i,3"]=$index
	((i += 1))
done < <(fold -w11 <<< "$BINARY_CONVERSION")

rows=$(printf '%s\n' "${!finalMatrix[@]}" | cut -d',' -f1 | sort -un | wc -l)

# Print a table of the results
declare -A filtered25Words
j=1
i=1
firstThreeCharactersOfEachWord=""

while : ; do
	
	if [[ $i -ge ${rows} || $j -gt $((SEED_WORDS)) ]]; then
		break
	fi

	# Monero have 1626 words but 11 bits have 2048 values, 
	# so if it's returned a value above the last word
	# ignore it and go to the next value achieved.
    if [[ ${finalMatrix["$i,1"]} -le $LAST_WORD_INDEX ]]; then
		filtered25Words["$j,0"]=${finalMatrix[$i,0]}
		filtered25Words["$j,1"]=${finalMatrix[$i,1]}
		filtered25Words["$j,2"]=${finalMatrix[$i,2]}
		filtered25Words["$j,3"]=$j
		firstThreeCharactersOfEachWord+="${filtered25Words[$j,2]:0:3}"
		((j += 1))
    fi
	
	((i += 1))
done


if [[ $j -ne $((SEED_WORDS+1)) ]]; then 
	echo "ERROR: the entropy inserted generated much wrong values, you need to add or remove any value to change the result and retry"	
	exit 1
fi

# Calculate the CRC32 checksum of the concatenated string. In this case, the checksum gives us the decimal number
checksum=$(printf '%s' $firstThreeCharactersOfEachWord | gzip -1 -c | tail -c8 | od -t u4 -N 4 -A n)   

# Take the checksum index modulo 24
wordIndex=$(( (checksum % SEED_WORDS) + 1 ))

twentyfivestWord=${filtered25Words[${wordIndex},2]}

echo -e "CHECKSUM WORD $twentyfivestWord \n"

printf "%-8s %-15s %-10s %-20s\n" "Position" "Binary" "Decimal+1" "Word"
printf "%s\n" "---------------------------------------"

for ((j=1; j<=${SEED_WORDS}; j++)); do
	printf "%-8s %-15s %-10s %-20s\n" "${filtered25Words[$j,3]}" "${filtered25Words[$j,0]}" "${filtered25Words[$j,1]}" "${filtered25Words[$j,2]}"
done

# Add the 25th word to the list, the checksum
filtered25Words["25,0"]=""
filtered25Words["25,1"]=0
filtered25Words["25,2"]=$twentyfivestWord
filtered25Words["25,3"]=25
printf "%-8s %-15s %-10s %-20s\n" "${filtered25Words[25,3]}" "${filtered25Words[25,0]}" "${filtered25Words[25,1]}" "${filtered25Words[25,2]}"

# Print inline seed words
printf "\nSEED WORDS:\n"
printf '=%.0s' $(seq 1 $((COLUMNS)))
printf "\n"
for i in $(seq 1 $((SEED_WORDS+1))); do
    printf "%s " "${filtered25Words[$i,2]}"
done
printf "\n"
printf '=%.0s' $(seq 1 $((COLUMNS)))
printf "\n"